apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "django-app-db.cwvq668i83q3.us-east-1.rds.amazonaws.com"
  POSTGRES_DB:   "django_app"
  POSTGRES_PORT: "5432"
